version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rupeetravel-api"
s3_bucket = "rupeetravel-api-deployment-artifacts"
s3_prefix = "rupeetravel-api"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
